apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: okd-fcos

resources:
  - ../../argo-workflows/okd-workflows
  - ../../buildconfigs

patches:
  - patch: |-
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: not-used
        labels:
          change-build-arg-tags: ""
      spec:
        strategy:
          dockerStrategy:
            buildArgs:
              - name: "TAGS"
                value: "fcos"
    target:
      labelSelector: "change-build-arg-tags==true"
      kind: BuildConfig
  - patch: |-
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: baremetal-installer
        labels:
          change-build-arg-tags: ""
      spec:
        strategy:
          dockerStrategy:
            buildArgs:
              - name: "TAGS"
                value: "fcos libvirt baremetal"
    target:
      kind: BuildConfig
      name: baremetal-installer
  - patch: |-
      - op: add
        path: "/spec/tags/-"
        value:
          name: fedora-coreos
          from:
            kind: DockerImage
            name: quay.io/fedora/fedora-coreos:next-devel
          referencePolicy:
            type: Source
    target:
      kind: ImageStream
      name: tools
