kind: List
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: build-manager
      annotations:
        description: |
          This role will allow the bound service account to manage builds and get buildconfigs.
          It is needed by the service account adapting the BuildConfigs into Builds to create and control.
    rules:
      - apiGroups:
          - ""
          - build.openshift.io
        resources:
          - builds
        verbs:
          - get
          - create
          - update
          - delete
      - apiGroups:
          - ""
          - build.openshift.io
        resources:
          - buildconfigs
        verbs:
          - get
      - apiGroups:
          - image.openshift.io
        resources:
          - imagestreams
          - imagestreamimports
        verbs:
          # handle the cleanup of the release imagestream
          - delete
          - create
          - get
      - apiGroups:
        - image.openshift.io
        resources:
        - imagestreamtags
        verbs:
          - create
          - delete
          - get
          - patch
          - list
          - update
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: argo-workflows-controller
      annotations:
        description: |
          This role is needed to allow the output parameters handling and to set the finalizers of the workflows objects
          when the setOwnerReference field is used by their steps.
    rules:
      - apiGroups:
          - argoproj.io
        resources:
          - workflowtaskresults
          - workflows/finalizers
        verbs:
          - create
          - get
          - patch
          - delete
          - update
      - apiGroups:
          - argoproj.io
        resources:
          - workflows
        verbs:
          - create
          - get
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: workflows-build-manager
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: build-manager
    subjects:
      - kind: ServiceAccount
        name: workflows
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: workflows-argo-workflows-exec
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: argo-workflows-controller
    subjects:
      - kind: ServiceAccount
        name: workflows
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: argo-image-builder
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:image-builder
    subjects:
      - kind: ServiceAccount
        name: workflows