apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-multiarch-image
spec:
  ttlStrategy:
    secondsAfterFailure: 259200 # 3 days
    secondsAfterSuccess: 86400  # 1 day
  entrypoint: entrypoint
  arguments:
    parameters:
      - name: build-config-name
        description: The name of a build config to use as source for the multiarch build
      - name: repo-url
        default: ""
        description: | 
          If a non-empty value is set for repo-url, the workflow will replace the URL of the source repo in 
          the BuildConfig. This and branch are useful to test content from PR that are not merged yet.
      - name: branch
        default: ""
        description: |
          If a non-empty value is set for branch, the workflow will replace the ref of the source repo in the 
          BuildConfig. This and repo-url are useful to test content from PR that are not merged yet.
      - name: architectures
  templates:
    - name: entrypoint
      steps:
        - - name: generate-params
            template: csv-to-json-array
            arguments:
              parameters:
                - name: list
                  value: "{{workflow.parameters.architectures}}"
        - - name: build-single-arch-manifests
            template: build-single-arch-manifest
            arguments:
              parameters:
                - name: build-config-name
                  value: "{{workflow.parameters.build-config-name}}"
                - name: repo-url
                  value: "{{workflow.parameters.repo-url}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
                - name: architecture
                  value: "{{item}}"
            withParam: "{{steps.generate-params.outputs.result}}"
        - - name: compose-manifest-list
            template: compose-manifest-list
            arguments:
              parameters:
                - name: final-image
                  value: "{{steps.build-single-arch-manifests.outputs.parameters.final-image}}"
                - name: architectures
                  value: "{{workflow.parameters.architectures}}"
    - name: build-single-arch-manifest
      inputs:
        parameters:
          - name: architecture
            description: The architecture to build the manifest for
          - name: build-config-name
          - name: repo-url
          - name: branch
      outputs:
        parameters:
          - name: final-image
            valueFrom:
              parameter: "{{steps.build-generate.outputs.parameters.final-image}}"
      steps:
        - - name: build-generate
            template: build-generate
            arguments:
              parameters:
                - name: architecture
                  value: "{{inputs.parameters.architecture}}"
                - name: build-config-name
                  value: "{{inputs.parameters.build-config-name}}"
                - name: repo-url
                  value: "{{inputs.parameters.repo-url}}"
                - name: branch
                  value: "{{inputs.parameters.branch}}"
        - - name: build-run-and-wait
            template: build-run-and-wait
            arguments:
              parameters:
                - name: build
                  value: "{{steps.build-generate.outputs.parameters.build}}"
    - name: build-generate
      inputs:
        parameters:
          - name: architecture
          - name: build-config-name
          - name: repo-url
          - name: branch
      outputs:
        parameters:
          - name: build
            valueFrom:
              path: /tmp/build.yaml
          - name: final-image
            valueFrom:
              path: /tmp/final-image
      script:
        # TODO: Can I use a resource template + action get + jqFilter in the output?
        image: quay.io/okd/payload-workflows:latest
        command:
          - bash
        source: |
          #!/bin/bash
          set -xeo pipefail
          yq eval-all '
            select(fileIndex == 0) * select(fileIndex == 1) |
            del(.spec.failedBuildsHistoryLimit) |
            del(.status) |
            del(.spec.runPolicy) |
            del(.spec.successfulBuildsHistoryLimit) |
            del(.metadata.creationTimestamp) |
            del(.metadata.uid) |
            del(.metadata.resourceVersion) |
            del(.metadata.annotations) |
            .metadata.generateName = .metadata.name + "-{{inputs.parameters.architecture}}-" |
            .spec.output.to.name = .spec.output.to.name + "-{{inputs.parameters.architecture}}" |
            del(.metadata.name)
          ' \
            <(kubectl get "bc/{{inputs.parameters.build-config-name}}" -o yaml) - <<EOF | tee /tmp/build.yaml
            kind: Build
            spec:
              nodeSelector: 
                kubernetes.io/arch: {{inputs.parameters.architecture}}
          EOF
          
          [ -n "{{inputs.parameters.repo-url}}" ] && yq -i '.spec.source.git.uri = "{{inputs.parameters.repo-url}}"' /tmp/build.yaml
          [ -n "{{inputs.parameters.branch}}" ] && yq -i '.spec.source.git.ref = "{{inputs.parameters.branch}}"' /tmp/build.yaml
          
          image=$(yq -r '.spec.output.to.name' /tmp/build.yaml)
          namespace=$(yq -r '.spec.output.to.namespace' /tmp/build.yaml)
          if [ "$namespace" == "null" ]; then
            # Use the namespace associated with the service account running this container
            namespace=$(</var/run/secrets/kubernetes.io/serviceaccount/namespace)
          fi
          echo "image-registry.openshift-image-registry.svc:5000/$namespace/${image%-*}" > /tmp/final-image
    - name: build-run-and-wait
      inputs:
        parameters:
          - name: build
      resource:
        action: create
        setOwnerReference: true
        successCondition: status.phase in (Complete)
        failureCondition: status.phase in (Failed)
        manifest: |
          {{inputs.parameters.build}}
    - name: compose-manifest-list
      inputs:
        parameters:
          - name: final-image
          - name: architectures
      script:
        image: quay.io/okd/payload-workflows:latest
        command:
          - bash
        source: |
          #!/bin/bash
          set -euo pipefail
          image='{{inputs.parameters.final-image}}'
          image="${image%\",*}"
          image="${image#\[\"}"
          mapfile -t architectures < <(echo "{{inputs.parameters.architectures}}" | tr ',' '\n')
          echo "[INFO] Creating manifest list ${image} with manifests for architectures ${architectures[*]}"         
          MANIFEST_LIST="
          image: ${image}
          manifests:"
          for arch in "${architectures[@]}"; do
            MANIFEST_LIST="${MANIFEST_LIST}
            - image: ${image}-${arch}
              platform:
                architecture: ${arch}
                os: linux"
          done
          echo "${MANIFEST_LIST}"          
          mtl --insecure --username k8s --password "$(</var/run/secrets/kubernetes.io/serviceaccount/token)" \
            push from-spec <(echo "${MANIFEST_LIST}")
          
          echo "[INFO] Manifest list pushed to ${image}. Deleting individual manifests..."
          set -x
          image="${image#image-registry.openshift-image-registry.svc:5000/}"
          namespace="${image%%/*}"
          image="${image#*/}"
          for arch in "${architectures[@]}"; do
            oc delete -n ${namespace} istag "${image}-${arch}"
          done
          echo "[INFO] Done."
    - name: csv-to-json-array
      inputs:
        parameters:
          - name: list
      script:
        image: quay.io/okd/payload-workflows:latest
        command: [python]
        source: |
          import json
          l = "{{inputs.parameters.list}}"
          print(json.dumps(l.split(",")))
