apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: forked-dockerfiles
  labels:
    builder-replacement: skip
    skip-release-branch: "true"
    skip-replace-cli: "true"
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/okd-project/okd-payload-pipeline'
      ref: main
    contextDir: forks
    images: []
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'release:forked-dockerfiles'
