apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: baremetal-installer
  labels:
    change-build-arg-tags: "true"
    resources-profile: high
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/installer'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/baremetal-installer/Dockerfile.centos9
          destinationDir: "./images/baremetal"
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/baremetal/Dockerfile.centos9
      buildArgs:
        # are these tag really necessary here?
          - name: "TAGS"
            value: "baremetal libvirt okd"
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:baremetal-installer'
