apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hyperkube
  labels:
    resources-profile: high
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/kubernetes'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
          - sourcePath: /code/artifacts/Dockerfile.builder.centos9
            destinationDir: "./openshift-hack/images/hyperkube"
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath:  "./openshift-hack/images/hyperkube/Dockerfile.builder.centos9"
      from:
        kind: "ImageStreamTag"
        name: "release:base"
      env:
        - name: WHAT
          value: "cmd/kube-apiserver cmd/kube-controller-manager cmd/kube-scheduler cmd/kubelet cmd/watch-termination"
        - name: KUBE_BUILD_PLATFORMS
          value: ""
      buildArgs:
        - name: PKG_NAME
          value: openshift
        - name: SPEC_FILEPATH
          value: ./openshift.spec
        - name: PKG_GO_PATH
          value: /go/src/k8s.io/kubernetes
        - name: ARCHITECTURES
          value: ""
        - name: BIN_OUTPUT
          value: "_output/local/bin"
        - name: MAKE_ARGS
          value: >-
            -e
        - name: INSTALL_PKGS
          value: "krb5-devel"
        - name: INSTALL_PKGS_RUNTIME
          value: "iproute"
        - name: BIN_OUTPUT
          value: "_output/local/bin"
        - name: NAME
          value: OpenShift Kubernetes Server Commands
        - name: DESCRIPTION
          value: >
            OpenShift is a platform for developing,
            building, and deploying containerized applications.
        # are these tag really necessary here?
        - name: TAGS
          value: openshift,hyperkube
        - name: VERSIONS
          value: "kubernetes=1.25.0"
          # TODO ^^ dynamic handling from the pipeline
          # TODO VV refactor me (see forked dockerfile)
        - name: ADDITIONAL_BIN_FOLDER_FROM_REPO
          value: "openshift-hack/images/hyperkube"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:hyperkube'
