---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: okd-release-pipeline
  namespace: okd-team
spec:
  params:
    - description: The URL for the release controller to use
      name: release-controller
      type: string
      default: "https://origin-release.ci.openshift.org"
    - description: The release stream to use (e.g., 4.12.0-0.okd, 4.12.0-0.okd-scos)
      name: release-stream
      type: string
    - description: The app.ci imagestream to use for tagging (e.g., release or release-scos)
      name: release-imagestream
      type: string
    - description: The content mirror destination
      name: content-mirror-pushspec
      type: string
      default: "quay.io/zzlotnik/scos-content"
    - description: The release mirror destination
      name: release-mirror-pushspec
      type: string
      default: "quay.io/zzlotnik/scos-release"
    - description: The GitHub org/repo to release to
      name: github-org-repo
      type: string
      default: "cheesesashimi/okd-release-test"
  tasks:
    - name: build-pipeline-worker-image
      taskRef:
        name: batch-build
      params:
        - name: build_configs
          value:
          - tekton-worker-image-build
    - name: pick-release
      taskRef:
        name: pick-release
      params:
        - name: release-controller
          value: $(params.release-controller)
        - name: release-stream
          value: $(params.release-stream)
      runAfter:
        - build-pipeline-worker-image
    - name: verify-release
      taskRef:
        name: gpg-verify-release
      params:
        - name: release-digest
          value: $(tasks.pick-release.results.release-digest)
      runAfter:
        - pick-release
    - name: prepare-binaries
      taskRef:
        name: prepare-release-binaries
      params:
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: release-pullspec
          value: $(tasks.pick-release.results.release-pullspec)
        - name: gpg-secret-name
          value: okd-private-key
        - name: gpg-secret-key-name
          value: private.key
        - name: gpg-key-id
          value: maintainers@okd.io
      runAfter:
        - verify-release
      workspaces:
        - name: release-binaries
          workspace: release-binaries
    - name: mirror
      taskRef:
        name: mirror-release
      params:
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: release-pullspec
          value: $(tasks.pick-release.results.release-pullspec)
        - name: image-push-secret-name
          value: okd-okd-robot-pull-secret
        - name: release-mirror-pushspec
          value: $(params.release-mirror-pushspec)
        - name: content-mirror-pushspec
          value: $(params.content-mirror-pushspec)
      runAfter:
        - verify-release
    - name: prepare-release-notes
      taskRef:
        name: prepare-release-notes
      params:
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: mirrored-release-pullspec
          value: $(tasks.mirror.results.mirrored-pullspec)
      runAfter:
        - mirror
      workspaces:
        - name: release-binaries
          workspace: release-binaries
    - name: create-github-release
      taskRef:
        name: create-github-release
      params:
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: github-token-secret-name
          value: gh-token
        - name: github-token-secret-key
          value: gh-okd-token
        - name: github-org-repo
          value: $(params.github-org-repo)
      runAfter:
        - prepare-binaries
        - prepare-release-notes
        - mirror
      workspaces:
        - name: release-binaries
          workspace: release-binaries
    - name: update-release-channel
      taskRef:
        name: update-release-channel
      params:
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: mirrored-release-pullspec
          value: $(tasks.mirror.results.mirrored-pullspec)
        - name: release-imagestream
          value: $(params.release-imagestream)
        - name: ci-cluster-secret-name
          value: prow-okd-secret
        - name: ci-cluster-secret-key
          value: ci-prow-token
      runAfter:
        - create-github-release
  workspaces:
    - name: release-binaries
